/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrintRouteImport } from './routes/print'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRepaymentsRouteImport } from './routes/_authenticated/repayments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCalculatorRouteImport } from './routes/_authenticated/calculator'
import { Route as AuthenticatedArrearsRouteImport } from './routes/_authenticated/arrears'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAffordabilityRouteImport } from './routes/_authenticated/affordability'
import { Route as PrintReceiptsReceiptIdRouteImport } from './routes/print.receipts.$receiptId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepaymentsRoute = AuthenticatedRepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorRoute = AuthenticatedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArrearsRoute = AuthenticatedArrearsRouteImport.update({
  id: '/arrears',
  path: '/arrears',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAffordabilityRoute =
  AuthenticatedAffordabilityRouteImport.update({
    id: '/affordability',
    path: '/affordability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PrintReceiptsReceiptIdRoute = PrintReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => PrintRoute,
} as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/affordability': typeof AuthenticatedAffordabilityRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/arrears': typeof AuthenticatedArrearsRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/repayments': typeof AuthenticatedRepaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/print/receipts/$receiptId': typeof PrintReceiptsReceiptIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/affordability': typeof AuthenticatedAffordabilityRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/arrears': typeof AuthenticatedArrearsRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/repayments': typeof AuthenticatedRepaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/print/receipts/$receiptId': typeof PrintReceiptsReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/affordability': typeof AuthenticatedAffordabilityRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/arrears': typeof AuthenticatedArrearsRoute
  '/_authenticated/calculator': typeof AuthenticatedCalculatorRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/repayments': typeof AuthenticatedRepaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/print/receipts/$receiptId': typeof PrintReceiptsReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/print'
    | '/reset-password'
    | '/affordability'
    | '/applications'
    | '/arrears'
    | '/calculator'
    | '/customers'
    | '/loans'
    | '/notifications'
    | '/repayments'
    | '/reports'
    | '/search'
    | '/admin/audit'
    | '/admin/products'
    | '/admin/users'
    | '/applications/$applicationId'
    | '/customers/$customerId'
    | '/print/receipts/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/print'
    | '/reset-password'
    | '/affordability'
    | '/applications'
    | '/arrears'
    | '/calculator'
    | '/customers'
    | '/loans'
    | '/notifications'
    | '/repayments'
    | '/reports'
    | '/search'
    | '/'
    | '/admin/audit'
    | '/admin/products'
    | '/admin/users'
    | '/applications/$applicationId'
    | '/customers/$customerId'
    | '/print/receipts/$receiptId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/print'
    | '/reset-password'
    | '/_authenticated/affordability'
    | '/_authenticated/applications'
    | '/_authenticated/arrears'
    | '/_authenticated/calculator'
    | '/_authenticated/customers'
    | '/_authenticated/loans'
    | '/_authenticated/notifications'
    | '/_authenticated/repayments'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/users'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/customers/$customerId'
    | '/print/receipts/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrintRoute: typeof PrintRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repayments': {
      id: '/_authenticated/repayments'
      path: '/repayments'
      fullPath: '/repayments'
      preLoaderRoute: typeof AuthenticatedRepaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculator': {
      id: '/_authenticated/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthenticatedCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arrears': {
      id: '/_authenticated/arrears'
      path: '/arrears'
      fullPath: '/arrears'
      preLoaderRoute: typeof AuthenticatedArrearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affordability': {
      id: '/_authenticated/affordability'
      path: '/affordability'
      fullPath: '/affordability'
      preLoaderRoute: typeof AuthenticatedAffordabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/print/receipts/$receiptId': {
      id: '/print/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/print/receipts/$receiptId'
      preLoaderRoute: typeof PrintReceiptsReceiptIdRouteImport
      parentRoute: typeof PrintRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAffordabilityRoute: typeof AuthenticatedAffordabilityRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedArrearsRoute: typeof AuthenticatedArrearsRoute
  AuthenticatedCalculatorRoute: typeof AuthenticatedCalculatorRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRepaymentsRoute: typeof AuthenticatedRepaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAffordabilityRoute: AuthenticatedAffordabilityRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedArrearsRoute: AuthenticatedArrearsRoute,
  AuthenticatedCalculatorRoute: AuthenticatedCalculatorRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRepaymentsRoute: AuthenticatedRepaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PrintRouteChildren {
  PrintReceiptsReceiptIdRoute: typeof PrintReceiptsReceiptIdRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintReceiptsReceiptIdRoute: PrintReceiptsReceiptIdRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrintRoute: PrintRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
